Add all scripts

diff --git a/run b/run
--- a/run
+++ b/run
@@ -4,21 +4,31 @@ set -x
 model="icon_cy3"
 model_years="2021 2022 2023 2024"
 keep_vars="rlut rsdt rsut"
+subsets="\
+40S+_recalib_bsd_noprecip \
+40S+_recalib_bsd_noprecip_cyc \
+40S+_recalib_bsd_noprecip_nocyc \
+40S+_recalib_bsd_noprecip_cyc_2r \
+40S+_recalib_bsd_noprecip_nocyc_2r \
+40S+_recalib_bsd_noprecip_lts_stable \
+40S+_recalib_bsd_noprecip_lts_unstable \
+40-55S_recalib_bsd_noprecip \
+55S+_recalib_bsd_noprecip"
 
 task="$1"
 
 recalib () {
-	in="$1"
-	out="$2"
+	local in="$1"
+	local out="$2"
 	mkdir -p "$out"
 	parallel -t alcf lidar default "$in" "$out" cloud_threshold: 5e-6 bsd: 5e-6 keep_vars: { $keep_vars } :::: input/obs/sources/by_instrument/chm15k
 	parallel -t alcf lidar default "$in" "$out" cloud_threshold: 5e-6 bsd: 10e-6 keep_vars: { $keep_vars } :::: input/obs/sources/by_instrument/cl51
 }
 
 run_alcf () {
-	model="$1"
-	in="$2"
-	out="$3"
+	local model="$1"
+	local in="$2"
+	local out="$3"
 	mkdir -p "$out"
 	parallel -j 4 -u alcf auto model "$model" cl51 "$in" "$out" track: data/obs/track_hourly_40S+/{}.nc --track_lon_180 njobs: 4 keep_vars: { $keep_vars } :::: input/obs/sources/by_instrument/cl51_voyages
 	parallel -j 1 -u alcf auto model "$model" cl51 "$in" "$out" track: data/obs/track_hourly_40S+/{}.nc --track_lon_180 track_gap: 0 njobs: 16 keep_vars: { $keep_vars } :::: input/obs/sources/by_instrument/cl51_stations
@@ -26,54 +36,129 @@ run_alcf () {
 }
 
 filter () {
-	in="$1"
-	out="$2"
+	local in="$1"
+	local out="$2"
 	mkdir -p "$(dirname "$out")"
 	parallel -j1 -t bin/alcf_filter "$in" data/obs/track_hourly_40S+/{}.nc -40 "$out" :::: input/obs/sources/all
 }
 
 filter_sic () {
-	in="$1"
-	out="$2"
+	local in="$1"
+	local out="$2"
 	mkdir -p "$(dirname "$out")"
 	parallel -j1 bin/alcf_filter_sic "$in" data/obs/surface_sic/{}.nc "$out" :::: input/obs/sources/all
 }
 
 filter_lts () {
-	stab="$1"
-	in="$2"
-	out="$3"
+	local stab="$1"
+	local in="$2"
+	local out="$3"
 	mkdir -p "$(dirname "$out")"
 	parallel -j1 bin/alcf_filter_lts_eis lts "$stab" 12 "$in" "$out" :::: input/obs/sources/all
 }
 
 stats () {
-	in="$1"
-	out="$2"
-	filter1="$3"
-	filter2="$4"
-	filter3="$5"
+	local in="$1"
+	local out="$2"
+	local filter_noprecip="$3"
+	local filter_sic="$4"
+	local filter="$5"
 	mkdir -p "$(dirname "$out")"
-	parallel -t alcf stats "$in" "$out" filter_include: { "$filter1" "$filter2" "$filter3" } :::: input/obs/sources/all
+	parallel -t alcf stats "$in" "$out" filter_include: { "$filter_noprecip" "$filter_sic" "$filter" } keep_vars: { $keep_vars } --debug :::: input/obs/sources/all
+}
+
+stats_lat () {
+	local in="$1"
+	local out="$2"
+	local filter_noprecip="$3"
+	local filter_sic="$4"
+	local lat1="$5"
+	local lat2="$6"
+	mkdir -p "$(dirname "$out")"
+	parallel -t alcf stats "$in" "$out" filter_include: { "$filter_noprecip" "$filter_sic" } lat_lim: { "$lat1" "$lat2" } keep_vars: { $keep_vars } --debug :::: input/obs/sources/all
 }
 
 stats_all () {
+	local in="$1"
+	local out="$2"
+	local filter_noprecip="$3"
+	local filter_sic="$4"
+	local filter_cyc="$5"
+	local filter_nocyc="$6"
+	local filter_cyc_2r="$7"
+	local filter_nocyc_2r="$8"
+	local filter_lts_stable="$9"
+	local filter_lts_unstable="${10}"
+	local year="${11}"
+	#local prefix=recalib_bsd_noprecip_sic
+	#stats "$in" "$out/40S+_$prefix/$year/{}.nc" "$filter_noprecip/{}.nc" "$filter_sic/{}.nc"
+	#stats "$in" "$out/40S+_${prefix}_cyc/$year/{}.nc" "$filter_noprecip/{}.nc" "$filter_sic/{}.nc" "$filter_cyc/{}.nc" 
+	#stats "$in" "$out/40S+_${prefix}_nocyc/$year/{}.nc" "$filter_noprecip/{}.nc" "$filter_sic/{}.nc" "$filter_nocyc/{}.nc" 
+	#stats "$in" "$out/40S+_${prefix}_cyc_2r/$year/{}.nc" "$filter_noprecip/{}.nc" "$filter_sic/{}.nc" "$filter_cyc_2r/{}.nc"
+	#stats "$in" "$out/40S+_${prefix}_nocyc_2r/$year/{}.nc" "$filter_noprecip/{}.nc" "$filter_sic/{}.nc" "$filter_nocyc_2r/{}.nc"
+	#stats "$in" "$out/40S+_${prefix}_lts_stable/$year/{}.nc" "$filter_noprecip/{}.nc" "$filter_sic/{}.nc" "$filter_lts_stable/{}.nc"
+	#stats "$in" "$out/40S+_${prefix}_lts_unstable/$year/{}.nc" "$filter_noprecip/{}.nc" "$filter_sic/{}.nc" "$filter_lts_unstable/{}.nc"
+	#stats_lat "$in" "$out/40-55S_$prefix/$year/{}.nc" "$filter_noprecip/{}.nc" "$filter_sic/{}.nc" -55 -40
+	#stats_lat "$in" "$out/55S+_$prefix/$year/{}.nc" "$filter_noprecip/{}.nc" "$filter_sic/{}.nc" -90 -55
+	local prefix=recalib_bsd_noprecip
+	stats "$in" "$out/40S+_$prefix/$year/{}.nc" "$filter_noprecip/{}.nc" ""
+	stats "$in" "$out/40S+_${prefix}_cyc/$year/{}.nc" "$filter_noprecip/{}.nc" "" "$filter_cyc/{}.nc" 
+	stats "$in" "$out/40S+_${prefix}_nocyc/$year/{}.nc" "$filter_noprecip/{}.nc" "" "$filter_nocyc/{}.nc" 
+	stats "$in" "$out/40S+_${prefix}_cyc_2r/$year/{}.nc" "$filter_noprecip/{}.nc" "" "$filter_cyc_2r/{}.nc"
+	stats "$in" "$out/40S+_${prefix}_nocyc_2r/$year/{}.nc" "$filter_noprecip/{}.nc" "" "$filter_nocyc_2r/{}.nc"
+	stats "$in" "$out/40S+_${prefix}_lts_stable/$year/{}.nc" "$filter_noprecip/{}.nc" "" "$filter_lts_stable/{}.nc"
+	stats "$in" "$out/40S+_${prefix}_lts_unstable/$year/{}.nc" "$filter_noprecip/{}.nc" "" "$filter_lts_unstable/{}.nc"
+	stats_lat "$in" "$out/40-55S_$prefix/$year/{}.nc" "$filter_noprecip/{}.nc" "" -55 -40
+	stats_lat "$in" "$out/55S+_$prefix/$year/{}.nc" "$filter_noprecip/{}.nc" "" -90 -55
+}
+
+stats_reanalysis () {
+	prefix="data/$1"
+	filter="$prefix/filter"
+	stats_all \
+		"$prefix/samples/{}/lidar_recalib_bsd" \
+		"$prefix/stats" \
+		"$filter/40S+_noprecip_thres0.1" \
+		"$filter/sic" \
+		"data/obs/filter/cyc" \
+		"data/obs/filter/nocyc" \
+		"data/obs/filter/cyc_2r" \
+		"data/obs/filter/nocyc_2r" \
+		"$filter/lts_stable" \
+		"$filter/lts_unstable"
+}
+
+rs () {
+	type_="$1"
+	in="$2"
+	out="$3"
+	parallel "mkdir -p $out/{}; bin/rs_profile $type_ data/obs/rs/locations/{}.csv $in/{} -40 $out/{}" :::: input/obs/sources/rs
+}
+
+rs_rstool () {
 	in="$1"
 	out="$2"
-	filter="$3"
-	filter_noprecip="$4"
-	filter_sic="$5"
-	year="$6"
-	prefix=recalib_bsd_noprecip_sic
-	stats "$in" "$out/40S+_$prefix/$year/{}.nc" "$filter_precip/$year/{}.nc" "$filter_sic/$year/{}.nc"
-	stats "$in" "$out/40S+_${prefix}_cyc/$year/{}.nc" "$filter_precip/$year/{}.nc" "$filter/cyc/$year/{}.nc" "$filter_sic/$year/{}.nc"
-	stats "$in" "$out/40S+_${prefix}_nocyc/$year/{}.nc" "$filter_precip/$year/{}.nc" "$filter/nocyc/$year/{}.nc" "$filter_sic/$year/{}.nc"
-	stats "$in" "$out/40S+_${prefix}_cyc_2r/$year/{}.nc" "$filter_precip/$year/{}.nc" "$filter/cyc_2r/$year/{}.nc" "$filter_sic/$year/{}.nc"
-	stats "$in" "$out/40S+_${prefix}_nocyc_2r/$year/{}.nc" "$filter_precip/$year/{}.nc" "$filter/nocyc_2r/$year/{}.nc" "$filter_sic/$year/{}.nc"
-	stats "$in" "$out/40S+_${prefix}_lts_stable/$year/{}.nc" "$filter_precip/$year/{}.nc" "$filter/lts_stable/$year/{}.nc" "$filter_sic/$year/{}.nc"
-	stats "$in" "$out/40S+_${prefix}_lts_unstable/$year/{}.nc" "$filter_precip/$year/{}.nc" "$filter/lts_unstable/$year/{}.nc" "$filter_sic/$year/{}.nc"
-	stats_lat "$in" "$out/40-55S_$prefix/$year/{}.nc" "$filter_precip/$year/{}.nc" "$filter_sic/$year/{}.nc" -55 -40
-	stats_lat "$in" "$out/55S+_$prefix/$year/{}.nc" "$filter_precip/$year/{}.nc" "$filter_sic/$year/{}.nc" -90 -55
+	for src in $(cat input/obs/sources/rs); do
+		mkdir -p "$out/$src"
+		parallel "echo {}; rstool prof prof {} $out/$src/{/}" ::: "$in/$src/"*.nc
+	done
+}
+
+rs_stats () {
+	in="$1"
+	filter="$2"
+	out="$3"
+	year="$4"
+	for subset in cyc_2r nocyc_2r lts_stable lts_unstable; do
+		mkdir -p "$out/40S+_$subset/$year"
+		parallel bin/rs_stats "$in"/{} "$filter/$subset/$year"/{}.nc -90 -40 "$out/40S+_$subset"/$year/{}.nc :::: input/obs/sources/rs 
+	done		
+	mkdir -p "$out/40S+/$year"
+	mkdir -p "$out/40-55S/$year"
+	mkdir -p "$out/55S+/$year"
+	parallel bin/rs_stats "$in"/{} -90 -40 "$out/40S+/$year"/{}.nc :::: input/obs/sources/rs 
+	parallel bin/rs_stats "$in"/{} -55 -40 "$out/40-55S/$year"/{}.nc :::: input/obs/sources/rs 
+	parallel bin/rs_stats "$in"/{} -90 -55 "$out/55S+/$year"/{}.nc :::: input/obs/sources/rs 
 }
 
 case "$task" in
@@ -111,8 +196,9 @@ recalib_obs)
 
 recalib_model)
 	for year in $model_years; do
-		recalib "input/$model/$year/{}/lidar" "data/$model/samples/$year/{}/lidar_recalib_bsd" none
+		recalib "input/$model/$year/{}/lidar" "data/$model/samples/$year/{}/lidar_recalib_bsd" none &
 	done
+	wait
 	;;
 
 recalib_merra2)
@@ -125,15 +211,16 @@ recalib_era5)
 
 alcf_ceres_obs)
 	for src in $(cat input/obs/sources/all); do
-		mkdir -p "data/obs/samples/$src/lidar_recalib_bsd_rad"
-		parallel bin/alcf_ceres {} input/ceres/ "data/obs/samples/$src/lidar_recalib_bsd_rad/{/}" ::: "data/obs/samples/$src/lidar_recalib_bsd/"*.nc
+		mkdir -p "data/obs/samples/$src/lidar_recalib_bsd"
+		parallel bin/alcf_ceres {} input/ceres/ "data/obs/samples/$src/lidar_recalib_bsd/{/}" ::: "data/obs/samples/$src/lidar_recalib_bsd/"*.nc
 	done
 	;;
 
 filter_model)
 	for year in $model_years; do
-		filter "input/$model/$year/{}/model" "data/$model/filter/40S+_noprecip_thres0.1/$year/{}.nc"
+		filter "input/$model/$year/{}/model" "data/$model/filter/40S+_noprecip_thres0.1/$year/{}.nc" &
 	done
+	wait
 	;;
 
 filter_merra2)
@@ -146,8 +233,9 @@ filter_era5)
 
 filter_sic)
 	for year in $model_years; do
-		filter_sic "input/$model/$year/{}/model" "data/$model/filter/sic/$year/{}.nc"
+		filter_sic "input/$model/$year/{}/model" "data/$model/filter/sic/$year/{}.nc" &
 	done
+	wait
 	;;
 
 filter_sic_merra2)
@@ -170,27 +258,56 @@ filter_lts_era5)
 
 filter_lts_model)
 	for year in $model_years; do
-		filter_lts stable "input/$model/$year/{}/model" "data/$model/filter/lts_stable/$year/{}.nc"
-		filter_lts unstable "input/$model/$year/{}/model" "data/$model/filter/lts_unstable/$year/{}.nc"
+		filter_lts stable "input/$model/$year/{}/model" "data/$model/filter/lts_stable/$year/{}.nc" &
+		filter_lts unstable "input/$model/$year/{}/model" "data/$model/filter/lts_unstable/$year/{}.nc" &
 	done
+	wait
 	;;
 
 stats_model)
+	prefix="data/$model"
+	filter="$prefix/filter"
 	for year in $model_years; do
-		stats_all "data/$model/samples/$year/{}/lidar_recalib_bsd" "data/$model/stats" "data/$model/filter" "data/$model/filter/40S+_noprecip_thres0.1" "data/$model/filter/sic" "$year"
+		stats_all \
+			"$prefix/samples/$year/{}/lidar_recalib_bsd" \
+			"$prefix/stats" \
+			"$filter/40S+_noprecip_thres0.1/$year" \
+			"$filter/sic/$year" \
+			"$filter/cyc/$year" \
+			"$filter/nocyc/$year" \
+			"$filter/cyc_2r/$year" \
+			"$filter/nocyc_2r/$year" \
+			"$filter/lts_stable/$year" \
+			"$filter/lts_unstable/$year" \
+			"$year" &
 	done
+	wait
 	;;
 
 stats_obs)
-	stats_all data/obs/samples/{}/lidar_recalib_bsd "data/$model/stats_obs" data/obs/filter data/obs/filter/40S+_noprecip "data/$model/filter/sic" ""
+	for year in $model_years; do
+		stats_all \
+			data/obs/samples/{}/lidar_recalib_bsd \
+			"data/$model/stats_obs" \
+			data/obs/filter/40S+_noprecip \
+			"data/$model/filter/sic/$year" \
+			data/obs/filter/cyc \
+			data/obs/filter/nocyc \
+			data/obs/filter/cyc_2r \
+			data/obs/filter/nocyc_2r \
+			data/era5/filter/lts_stable \
+			data/era5/filter/lts_unstable \
+			"$year" &
+	done
+	wait
 	;;
 
 stats_merra2)
-	stats_all data/merra2/samples/{}/lidar_recalib_bsd data/merra2/stats data/merra2/filter data/merra2/filter/40S+_noprecip_thres0.1 data/merra2/filter/sic ""
-;;
+	stats_reanalysis merra2
+	;;
 
 stats_era5)
-	stats_all data/era5/samples/{}/lidar_recalib_bsd data/era5/stats data/era5/filter data/era5/filter/40S+_noprecip_thres0.1 data/era5/filter/sic ""
+	stats_reanalysis era5
 	;;
 
 calc_ta_sst_hist_model)
@@ -198,7 +315,7 @@ calc_ta_sst_hist_model)
 		parallel bin/calc_ta_sst_co_hist "$x" data/icon_surface_alcf/{}.nc data/icon_alcf/{}/lidar data/ta_sst_co_hist/icon_alcf/{}.nc :::: "input/voyages/model/$x"
 	done
 	bin/merge_ta_sst_co_hist data/ta_sst_co_hist/icon_alcf/ data/ta_sst_co_hist_icon_alcf.nc
-;;
+	;;
 
 calc_ta_sst_hist_obs)
 	parallel bin/calc_ta_sst_co_hist generic input/polarstern/surface/{}.nc input/polarstern/cl51/alcf/{}/lidar data/ta_sst_co_hist/obs/{}.nc :::: input/voyages/obs/polarstern
@@ -207,10 +324,139 @@ calc_ta_sst_hist_obs)
 	bin/calc_ta_sst_co_hist generic input/aa/marcus/surface_underway.nc input/aa/marcus/alcf_ceil/lidar data/ta_sst_co_hist/obs/marcus.nc
 	parallel bin/calc_ta_sst_co_hist generic input/aa/aa15-16/l1/underway/{}.nc input/aa/aa15-16/l2/cl51_alcf/lidar data/ta_sst_co_hist/obs/aa15-16_{}.nc ::: v1 v2 v3
 	bin/merge_ta_sst_co_hist data/ta_sst_co_hist/obs/ data/ta_sst_co_hist_obs.nc
-;;
+	;;
+
+plot_cl_agg)
+	mkdir -p plot/cl_agg
+	for subset in $subsets; do
+		bin/plot_cl_agg \
+			"data/icon_cy3/stats_obs/$subset/2021" \
+			"data/icon_cy3/stats/$subset" \
+			"data/merra2/stats/$subset" \
+			"data/era5/stats/$subset" \
+			ICON MERRA-2 ERA5 \
+			"plot/cl_agg/cy3_${subset}.pdf" &
+	done
+	wait
+	;;
+
+plot_clt_hist)
+	mkdir -p plot/clt_hist
+	for subset in $subsets; do
+		bin/plot_clt_hist \
+			"data/icon_cy3/stats_obs/$subset/2021" \
+			"data/icon_cy3/stats/$subset" \
+			"data/merra2/stats/$subset" \
+			"data/era5/stats/$subset" \
+			OBS ICON MERRA-2 ERA5 \
+			"plot/clt_hist/cy3_${subset}.pdf" &
+	done
+	wait
+	;;
+
+rs_model)
+	for year in $model_years; do
+		rs_rstool "input/$model/rs/$year" "data/icon_cy3/rs/profiles/$year" &
+	done
+	wait
+	;;
+
+#rs_obs)
+#	rs_rstool input/obs/rs/profiles data/obs/rs/profiles
+#	;;
+
+rs_obs)
+	for src in $(cat input/obs/sources/by_platform/ps); do
+		in="input/obs/rs/ps/$src"
+		out="data/obs/rs/profiles/$src"
+		mkdir -p "$out"
+		if [ -e "$in/tab_wo_header" ]; then
+			#parallel bin/rs_ps_single {} "data/obs/track/$src.nc"  "$in/summary_wo_header.tab" "$out/"{/.}.nc ::: "$in/tab_wo_header/"*.tab
+			true
+		elif [ -e "$in"/*_radiosonde_wo_header.tab ]; then
+			true
+		else
+			echo "$src: no radiosonde measurements found" >&2
+		fi
+	done
+	parallel '[ -e input/obs/rs/ps/{}/*_radiosonde_wo_header.tab ] && bin/rs_ps_multi input/obs/rs/ps/{}/*_radiosonde_wo_header.tab data/obs/rs/profiles/{}' :::: input/obs/sources/by_platform/ps
+	for src in $(cat input/obs/sources/by_platform/ps); do
+		parallel rstool prof prof {} "input/obs/surf/ps/$src.nc" {} ::: "data/obs/rs/profiles/$src"/*.nc
+	done
+	declare -A input_type
+	input_type[TAN1702]=imet
+	input_type[TAN1802]=imet
+	input_type[NBP1704]=prof
+	for src in TAN1702 TAN1802 NBP1704; do
+		mkdir -p "data/obs/rs/profiles/$src"
+		parallel rstool "${input_type[$src]}" prof {} "input/obs/surf/$src.nc" "data/obs/rs/profiles/$src/"{/.}.nc ::: "input/obs/rs/$src/"*
+	done
+	mkdir -p data/obs/rs/profiles/MARCUS
+	parallel bin/rs_marcus {} data/obs/rs/profiles/MARCUS/{/} ::: input/obs/rs/MARCUS/*.nc
+	parallel rstool prof prof {} input/obs/surf/MARCUS.nc {} ::: data/obs/rs/profiles/MARCUS/*.nc
+	;;
+
+rs_merra2)
+	rs merra2 input/merra2 data/merra2/rs/profiles
+	rs_rstool data/merra2/rs/profiles data/merra2/rs/profiles
+	;;
+
+rs_era5)
+	rs era5 input/era5 data/era5/rs/profiles
+	rs_rstool data/era5/rs/profiles data/era5/rs/profiles
+	;;
+
+rs_stats_obs)
+	rs_stats data/obs/rs/profiles data/obs/filter data/obs/rs/stats
+	;;
+
+rs_stats_model)
+	for year in $model_years; do
+		rs_stats "data/$model/rs/profiles/$year" "data/$model/filter" "data/$model/rs/stats" "$year" &
+	done
+	wait
+	;;
+
+rs_stats_merra2)
+	rs_stats data/merra2/rs/profiles data/merra2/filter data/merra2/rs/stats
+	;;
+
+rs_stats_era5)
+	rs_stats data/era5/rs/profiles data/era5/filter data/era5/rs/stats
+	;;
+
+rs_stats_all)
+	./run rs_stats_obs
+	./run rs_stats_model
+	./run rs_stats_merra2
+	;;
+
+plot_rs_agg)
+	for subset in \
+		40S+ \
+		40S+_cyc_2r \
+		40S+_nocyc_2r \
+		40S+_lts_stable \
+		40S+_lts_unstable \
+		40-55S \
+		55S+
+	do
+		for type_ in theta_hur lcl; do
+			mkdir -p "plot/rs_agg/$type_"
+			bin/plot_rs_agg \
+				"$type_" \
+				"data/obs/rs/stats/$subset" \
+				"data/icon_cy3/rs/stats/$subset/2021" \
+				"data/merra2/rs/stats/$subset" \
+				"data/era5/rs/stats/$subset" \
+				OBS ICON MERRA-2 ERA5 \
+				"plot/rs_agg/$type_/$subset.pdf"
+		done
+	done
+	;;
 
 *)
-echo "Invalid task \"$task\"" >&2
-;;
+	echo "Invalid task \"$task\"" >&2
+	;;
 
 esac
